# Global settings
cellType: sphere

# Cell settings
cell:
  x:
    prob: 0.35
    mu: 0
    sigma: 10
  y:
    prob: 0.35
    mu: 0
    sigma: 10
  z:
    prob: 0.25
    mu: 0
    sigma: 10
  radius:
    prob: 0.1
    mu: 0
    sigma: 3
  minRadius: 4
  maxRadius: 24

# Simulation settings
simulation:
  iterations_per_cell: 1
  background_color: 0.376
  cell_color: 0.496
  padding: 0
  z_scaling: 6.925
  blur_sigma: 2
